package utils

import (
    "encoding/base64"
    "unicode/utf16"
    "encoding/binary"
    "bytes"
    "strings"
    "math/rand"
    "os"
    "log"
    b64 "encoding/base64"
    "regexp"
    _ "archive/zip"
    _ "io"

)

const (
    TEMP_OUTPUT_DIRECTORY = "./temp_outfile"
)

//var rng = rand.New(rand.NewSource(time.Now().UnixNano()))

func EncodeStringToUTF16Base64(s string) string {
    // Convert string to UTF-16 code units
    utf16Encoded := utf16.Encode([]rune(s))

    // Convert UTF-16 code units to bytes (Little Endian)
    buf := new(bytes.Buffer)
    for _, r := range utf16Encoded {
        binary.Write(buf, binary.LittleEndian, r)
    }

    // Encode bytes to Base64
    return base64.StdEncoding.EncodeToString(buf.Bytes())
}

func StringToSlice(s string) []string{
    return strings.Split(s, "\n")
}

// Generated by Claude
// For splitting a one-line string into slices
func StringToSliceRandomLengths(s string, minLen, maxLen int) []string {
    runes := []rune(s)
    var result []string

    for i := 0; i < len(runes); {
        chunkSize := minLen + rand.Intn(maxLen-minLen+1)
        end := i + chunkSize
        if end > len(runes) {
            end = len(runes)
        }
        result = append(result, string(runes[i:end]))
        i = end
    }

    return result
}

func SliceToString(s []string) string{
    return strings.Join(s, "\n")
}

func SliceToStringOneLine(s []string) string{
    return strings.Join(s, "")
}

func EscapeJScriptString(s string) string {
    return strings.ReplaceAll(s, `"`, `\"`)
}

func EscapePowerShellString(s string) string {
    replacer := strings.NewReplacer(
        "`", "``",   // backtick is the PS escape character — must be first
        "\"", "`\"",   // double quote
        "$", "`$",   // variable sigil — prevents unintended variable expansion
        "`n", "``n", // literal backtick-n — prevent misinterpretation as newline
        "`t", "``t", // literal backtick-t — prevent misinterpretation as tab
        "\r", "`r",  // carriage return
        "\n", "`n",  // newline
        "\t", "`t",  // tab
    )
    return replacer.Replace(s)
}

// Returns b64 encoded content
func Base64EncodeFile(filepath string) string{
    originalContent, err := os.ReadFile(filepath)
    if err != nil{
        log.Fatal(err)
    }

    return b64.StdEncoding.EncodeToString(originalContent)
}

func Base64EncodeString(s string) string{
    return b64.StdEncoding.EncodeToString([]byte(s))
}

func RemovePowershellComments(lines []string) []string {
    // Matches single-line comments (#) and block comments (<# ... #>)
    singleLineComment := regexp.MustCompile(`(?i)^\s*#.*$`)
    inlineComment     := regexp.MustCompile(`(?i)\s*#[^"']*$`)
    blockCommentStart := regexp.MustCompile(`(?i)<#`)
    blockCommentEnd   := regexp.MustCompile(`(?i)#>`)

    result := []string{}
    inBlockComment := false

    for _, line := range lines {
        // Handle block comment start/end
        if blockCommentStart.MatchString(line) {
            inBlockComment = true
        }
        if inBlockComment {
            if blockCommentEnd.MatchString(line) {
                inBlockComment = false
            }
            continue
        }

        // Skip full-line comments
        if singleLineComment.MatchString(line) {
            continue
        }

        // Strip inline comments
        line = inlineComment.ReplaceAllString(line, "")

        if line != "" {
            result = append(result, line)
        }
    }
    return result
}

func RemoveJavascriptComments(lines []string) []string {
    singleLineComment := regexp.MustCompile(`^\s*//.*$`)
    inlineComment     := regexp.MustCompile(`\s*//.*$`)
    blockCommentStart := regexp.MustCompile(`/\*`)
    blockCommentEnd   := regexp.MustCompile(`\*/`)

    result := []string{}
    inBlockComment := false

    for _, line := range lines {
        // Handle block comment start/end
        if blockCommentStart.MatchString(line) {
            inBlockComment = true
        }
        if inBlockComment {
            if blockCommentEnd.MatchString(line) {
                inBlockComment = false
            }
            continue
        }

        // Skip full-line comments
        if singleLineComment.MatchString(line) {
            continue
        }

        // Strip inline comments
        line = inlineComment.ReplaceAllString(line, "")

        if line != "" {
            result = append(result, line)
        }
    }
    return result
}