package utils

import (
    "fmt"
    "os"
    "bufio"
    "strings"
    "math/rand"
    "time"
    "slices"
    "regexp"
)

const (
    WORDLIST_LARGE = "./utils/word-list-large.txt"
    letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
)



// Generated with Claude
// Both slice will preserve its order
func InsertRandomly(slice1, slice2 []string) []string {
    rand.Seed(time.Now().UnixNano())

    totalLen := len(slice1) + len(slice2)
    result := make([]string, totalLen)

    // randomly pick positions for slice2 elements
    positions := rand.Perm(totalLen)[:len(slice2)]
    slices.Sort(positions)

    // place slice2 elements at chosen positions
    for i, pos := range positions {
        result[pos] = slice2[i]
    }

    // fill remaining positions with slice1 elements in order
    j := 0
    for i, val := range result {
        if val == "" && j < len(slice1) {
            result[i] = slice1[j]
            j++
        }
    }

    return result
}

// Generated by Claude
func InsertRandomComments(lines []string, wordListFile string, wordsPerComment, numComments int) ([]string, error) {
    // read and parse wordlist
    content, err := os.ReadFile(wordListFile)
    if err != nil {
        return nil, fmt.Errorf("[-] Failed to read wordlist: %w", err)
    }

    var words []string
    scanner := bufio.NewScanner(strings.NewReader(string(content)))
    for scanner.Scan() {
        if word := strings.TrimSpace(scanner.Text()); word != "" {
            words = append(words, word)
        }
    }

    if len(words) == 0 {
        return nil, fmt.Errorf("[-] Wordlist is empty")
    }

    // generate random comments
    comments := make([]string, numComments)
    for i := range comments {
        selected := make([]string, wordsPerComment)
        for j := range selected {
            selected[j] = words[rand.Intn(len(words))]
        }
        comments[i] = "// " + strings.Join(selected, " ")
    }

    // insert comments randomly into lines preserving order
    return InsertRandomly(lines, comments), nil
}

func RandRange(min, max int) int{
    if (max < min){
        fmt.Println("[-] RandRange range error: min > max.")
        return 0
    }
    return rand.Intn(max-min) + min
}


// Generated by Claude
// Word list used for replacements

var defaultWordList = []string{
    "apple", "bridge", "canvas", "delta", "ember", "frost", "globe", "haven",
    "inlet", "jewel", "karma", "lunar", "maple", "noble", "ocean", "prism",
    "quill", "raven", "solar", "thorn", "umbra", "vapor", "waltz", "xenon",
    "yacht", "zephyr", "amber", "blaze", "coral", "dusk", "eagle", "flint",
    "gravel", "haze", "ivory", "jade", "knoll", "latch", "mist", "nexus",
    "obsid", "petal", "quartz", "ridge", "slate", "tidal", "ultra", "vixen",
    "wrath", "xylem", "yield", "zonal", "acorn", "birch", "cedar", "drift",
    "epoch", "fable", "glyph", "helix", "igloo", "joust", "kiosk", "lance",
    "manor", "nymph", "onset", "pixel", "quota", "realm", "sigma", "trove",
    "umbel", "viola", "whirl", "xeric", "yearn", "zippy", "axiom", "brink",
    "crest", "dwarf", "envoy", "forge", "guild", "horde", "index", "jumbo",
}


/* For JScript*/
// JScript reserved words and built-ins that must not be renamed
var jsReserved = map[string]bool{
    // Language keywords
    "break": true, "case": true, "catch": true, "continue": true,
    "debugger": true, "default": true, "delete": true, "do": true,
    "else": true, "finally": true, "for": true, "function": true,
    "if": true, "in": true, "instanceof": true, "new": true,
    "return": true, "switch": true, "this": true, "throw": true,
    "try": true, "typeof": true, "var": true, "void": true,
    "while": true, "with": true, "true": true, "false": true, "null": true,

    // Built-in objects and functions
    "ActiveXObject": true, "WScript": true, "WSH": true, "Shell": true,
    "Scripting": true, "FileSystemObject": true, "Object": true,
    "Array": true, "String": true, "Number": true, "Boolean": true,
    "Date": true, "Math": true, "RegExp": true, "Error": true,
    "JSON": true, "parseInt": true, "parseFloat": true, "isNaN": true,
    "isFinite": true, "decodeURI": true, "encodeURI": true,
    "decodeURIComponent": true, "encodeURIComponent": true,
    "eval": true, "undefined": true, "Infinity": true, "NaN": true,

    // WScript methods and properties
    "Echo": true, "Quit": true, "Sleep": true, "Arguments": true,
    "ScriptName": true, "ScriptFullName": true, "FullName": true,
    "Path": true, "Interactive": true, "Version": true, "BuildVersion": true,
    "StdIn": true, "StdOut": true, "StdErr": true, "CreateObject": true,
    "GetObject": true, "ConnectObject": true, "DisconnectObject": true,

    // Common JScript globals
    "window": true, "document": true, "console": true, "prototype": true,
    "constructor": true, "length": true, "toString": true, "valueOf": true,
    "hasOwnProperty": true, "charAt": true, "indexOf": true, "split": true,
    "replace": true, "match": true, "slice": true, "join": true,
    "push": true, "pop": true, "shift": true, "unshift": true,
    "forEach": true, "map": true, "filter": true, "reduce": true,
    "call": true, "apply": true, "bind": true, "log": true,
}


// pickWord returns a random word from the word list that hasn't been used yet
func pickWord(used map[string]bool, wordList []string) string {
    rng := rand.New(rand.NewSource(time.Now().UnixNano()))
    available := []string{}
    for _, w := range wordList {
        if !used[w] {
            available = append(available, w)
        }
    }
    if len(available) == 0 {
        // All words exhausted — generate a fallback random suffix
        return wordList[rng.Intn(len(wordList))] + randomSuffix()
    }
    return available[rng.Intn(len(available))]
}

func randomSuffix() string {
    const letters = "abcdefghijklmnopqrstuvwxyz"
    rng := rand.New(rand.NewSource(time.Now().UnixNano()))
    b := make([]byte, 4)
    for i := range b {
        b[i] = letters[rng.Intn(len(letters))]
    }
    return "_" + string(b)
}

// ObfuscateJScript takes a slice of JScript code lines, renames all
// user-defined variable and function names with random words, and
// returns the obfuscated lines.
func RenameJScriptVairables(lines []string, wordListFile string) []string {
    source := strings.Join(lines, "\n")

    nameMap := make(map[string]string) // original name -> replacement word
    usedWords := make(map[string]bool) // tracks used replacement words

    // read and parse wordlist
    content, err := os.ReadFile(wordListFile)
    if err != nil {
        return nil
    }

    var wordList []string
    scanner := bufio.NewScanner(strings.NewReader(string(content)))
    for scanner.Scan() {
        if word := strings.TrimSpace(scanner.Text()); word != "" {
            wordList = append(wordList, word)
        }
    }

    // --- Extract variable names ---
    // Matches: var foo, var foo = ..., also catches comma-separated: var a, b, c
    varRegex := regexp.MustCompile(`\bvar\s+([a-zA-Z_$][a-zA-Z0-9_$]*)`)
    for _, match := range varRegex.FindAllStringSubmatch(source, -1) {
        name := match[1]
        if !jsReserved[name] && nameMap[name] == "" {
            word := pickWord(usedWords, wordList)
            usedWords[word] = true
            nameMap[name] = word
        }
    }

    // --- Extract function names ---
    // Matches: function foo(...) and var foo = function(...)
    funcRegex := regexp.MustCompile(`\bfunction\s+([a-zA-Z_$][a-zA-Z0-9_$]*)`)
    for _, match := range funcRegex.FindAllStringSubmatch(source, -1) {
        name := match[1]
        if !jsReserved[name] && nameMap[name] == "" {
            word := pickWord(usedWords, wordList)
            usedWords[word] = true
            nameMap[name] = word
        }
    }

    // --- Apply replacements ---
    // Sort by length descending to prevent partial replacements
    // e.g. "foo" being replaced inside "fooBar"
    names := make([]string, 0, len(nameMap))
    for name := range nameMap {
        names = append(names, name)
    }
    sortByLengthDesc(names)

    for _, name := range names {
        // Use word boundary regex to replace whole identifiers only
        re := regexp.MustCompile(`\b` + regexp.QuoteMeta(name) + `\b`)
        source = re.ReplaceAllString(source, nameMap[name])
    }

    return strings.Split(source, "\n")
}

// sortByLengthDesc sorts a string slice by length descending (in place)
func sortByLengthDesc(s []string) {
    for i := 0; i < len(s); i++ {
        for j := i + 1; j < len(s); j++ {
            if len(s[j]) > len(s[i]) {
                s[i], s[j] = s[j], s[i]
            }
        }
    }
}

func GenerateRandomUnicodeString(length int) string {
    // Unicode ranges to sample from
    ranges := []struct{ lo, hi rune }{
        {0x0020, 0x007E},   // Basic Latin (printable ASCII)
        {0x00A0, 0x00FF},   // Latin-1 Supplement
        {0x0100, 0x017F},   // Latin Extended-A
        {0x0370, 0x03FF},   // Greek and Coptic
        {0x0400, 0x04FF},   // Cyrillic
        {0x4E00, 0x9FFF},   // CJK Unified Ideographs
        {0x1F300, 0x1F5FF}, // Miscellaneous Symbols and Pictographs (Emoji)
        {0x1F600, 0x1F64F}, // Emoticons
        {0x0600, 0x06FF},   // Arabic
        {0x0900, 0x097F},   // Devanagari
    }

    var sb strings.Builder
    for i := 0; i < length; i++ {
        // Pick a random range
        r := ranges[rand.Intn(len(ranges))]
        // Pick a random rune within that range
        ch := rune(r.lo + rune(rand.Intn(int(r.hi-r.lo+1))))
        sb.WriteRune(ch)
    }

    return sb.String()
}

func InsertJunkStringToSlice(s []string, len int) ([]string, string){
    junkString := GenerateRandomUnicodeString(len)

    var result []string

    for _, str := range s {
        str = str + junkString
        result = append(result, str)
    }


    return result, junkString
}

func RandomString(length int) string {
    rng := rand.New(rand.NewSource(time.Now().UnixNano()))
    b := make([]byte, length)
    for i := range b {
        b[i] = letters[rng.Intn(len(letters))]
    }
    return string(b)
}

var powershellSpecialVars = map[string]bool{
    "$null":              true,
    "$true":              true,
    "$false":             true,
    "$error":             true,
    "$home":              true,
    "$host":              true,
    "$pid":               true,
    "$profile":           true,
    "$psculture":         true,
    "$psuiculture":       true,
    "$psversiontable":    true,
    "$psscriptroot":      true,
    "$pscommandpath":     true,
    "$pwd":               true,
    "$args":              true,
    "$input":             true,
    "$myinvocation":      true,
    "$lastexitcode":      true,
    "$stacktrace":        true,
    "$foreach":           true,
    "$switch":            true,
    "$this":              true,
    "$env":               true,
}

// Generated using Claude
func ReplacePowershellVariables(lines []string) []string {
    varRegex := regexp.MustCompile(`\$\{[^}]+\}|\$[a-zA-Z_][a-zA-Z0-9_]*`)
    replacements := make(map[string]string)

    result := make([]string, len(lines))
    for i, line := range lines {
        result[i] = varRegex.ReplaceAllStringFunc(line, func(match string) string {
            // Normalise to lowercase for case-insensitive comparison
            if powershellSpecialVars[strings.ToLower(match)] {
                return match
            }
            if _, exists := replacements[match]; !exists {
                replacements[match] = "$" + RandomString(8)
            }
            return replacements[match]
        })
    }
    return result
}